### ISSUE TITLE
Crash On World Creation With Create

### ISSUE THREAD

**Issue by ChloeDawn** [MehVahdJukaar/Supplementaries#328]
**Mod version:** 1.18.2-1.4.7
**Create version:** 1.18.2-0.5.0.d
**Forge version:** 40.1.73

The game crashes when creating a world due to a missing method error.
Reproduced in an instance with only Create, Supplementaries, and their dependencies.

```
java.lang.NoSuchMethodError: 'void com.simibubi.create.AllMovementBehaviours.addMovementBehaviour(net.minecraft.world.level.block.Block, com.simibubi.create.content.contraptions.components.structureMovement.MovementBehaviour)'
```

[crash-2022-08-19_00.02.35-client.txt](https://github.com/MehVahdJukaar/Supplementaries/files/9378170/crash-2022-08-19_00.02.35-client.txt)

**Comment by copygirl** [comment]
Seems to work with Supplementaries 1.4.8?

**Comment by MehVahdJukaar** [comment]
yeah I didnt push the last updated. resolved now
